/// Represents the result of an AI chat interaction that may include
/// a Gemini Function Call decision (e.g. page navigation or travel plan creation).
class AIFunctionCallResult {
  const AIFunctionCallResult({
    required this.responseText,
    this.functionName,
    this.arguments,
  });

  /// The text message reply generated by Gemini.
  final String responseText;

  /// The name of the called function (e.g., 'navigateToPage', 'createTravelPlan'), if any.
  final String? functionName;

  /// Arguments provided by Gemini for the function call, if any.
  final Map<String, dynamic>? arguments;

  /// Returns true if Gemini invoked a function call.
  bool get hasFunctionCall => functionName != null && functionName!.isNotEmpty;

  @override
  String toString() {
    return 'AIFunctionCallResult(responseText: $responseText, functionName: $functionName, arguments: $arguments)';
  }
}
